GET http://localhost:3001/

### Get Users
GET http://localhost:3001/users

### Create User
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "new_user@example.com",
  "password": "securepassword",
  "name": "Test"
}

### Create Project
POST http://localhost:3001/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxc3BlZWQxQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzM0NDA5MTE2LCJleHAiOjE3MzQ0MTI3MTZ9.faBpPy8CPYp1_990lw973IXe96c58QtmK0kqWE9QKXw

{
  "title": "New Project",
  "description": "This is a new project",
  "start_date": "2023-10-01T00:00:00.000Z",
  "end_date": "2023-12-31T00:00:00.000Z",
  "status": "In Progress"
}

### Get User Projects
GET http://localhost:3001/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxc3BlZWQxQGdtYWlsLmNvbSIsInN1YiI6NCwiaWF0IjoxNzM0MzIzODMwLCJleHAiOjE3MzQzMjc0MzB9.pjBt7pAGMyMqnmYfTdl9kpZGYNdNhihgLDgrthaD5TY

### Create Task
POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "New Task",
  "description": "This is a new task",
  "progress_contribution": 10,
  "status": "Not Started",
  "due_date": "2023-11-01T00:00:00.000Z",
  "project_id": 1
}

### get tasks by project id
GET http://localhost:3001/tasks?project_id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxc3BlZWQxQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzM2ODA3Mzk5LCJleHAiOjE3MzY4MTA5OTl9.FWrB43ANrXNHM0ldHomxOvMZoHAt45jL-MK3DiL2caQ

### Create Completion
POST http://localhost:3001/completions
Content-Type: application/json

{
  "project_id": 1,
  "completion_date": "2023-11-01T00:00:00.000Z",
  "proof_url": "http://example.com/proof",
  "proof_image": "http://example.com/proof_image.jpg"
}

### Auth
Get http://localhost:3001/auth/google


### validate token
GET http://localhost:3001/auth/validate-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxc3BlZWQxQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzM1MjYzNjg1LCJleHAiOjE3MzUyNjcyODV9.6PMvnpu12ZBeVw_x0STWXsG7fWeIb8ckcu_2LbjE_9A